// FOR USERS

export const ADD_USER = 'ADD_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// FOR PINS

export const ADD_ITEM = 'ADD_ITEM'

// FOR FEATURE PICS

export const LOAD_FEATURE_FOLDER = 'LOAD_FEATURE_FOLDER'

//FOR PICTURES

export const LOAD_COMMENTS = 'LOAD_COMMENTS'
